from crosslingual_coreference import Predictor

predictor = Predictor(language='nl_core_news_sm')

text_en = """Paul Allen was born on January 21, 1953, in Seattle, Washington, to Kenneth Sam Allen and Edna Faye Allen. Allen attended Lakeside School, a private school in Seattle, where he befriended Bill Gates, two years younger, with whom he shared an enthusiasm for computers. Paul and Bill used a teletype terminal at their high school, Lakeside, to develop their programming skills on several time-sharing computer systems."""
text_nl = """Paul Allen werd geboren op 21 januari 1953 in Seattle, Washington, als zoon van Kenneth Sam Allen en Edna Faye Allen. Allen ging naar de Lakeside School, een privéschool in Seattle, waar hij bevriend raakte met Bill Gates, twee jaar jonger, met wie hij zijn enthousiasme voor computers deelde. Paul en Bill gebruikten een teletype-terminal op hun middelbare school, Lakeside, om hun programmeervaardigheden op verschillende timesharing-computersystemen te ontwikkelen."""
text_de = """Paul Allen wurde am 21. Januar 1953 in Seattle, Washington, als Sohn von Kenneth Sam Allen und Edna Faye Allen geboren. Allen besuchte die Lakeside School, eine Privatschule in Seattle, wo er sich mit dem zwei Jahre jüngeren Bill Gates anfreundete, mit dem er die Begeisterung für Computer teilte. Paul und Bill nutzten ein Fernschreibterminal an ihrer Highschool Lakeside, um ihre Programmierkenntnisse auf mehreren Time-Sharing-Computersystemen zu entwickeln."""
text_dk = """Paul Allen blev født den 21. januar 1953 i Seattle, Washington, af Kenneth Sam Allen og Edna Faye Allen. Allen gik på Lakeside School, en privatskole i Seattle, hvor han blev ven med Bill Gates, to år yngre, som han delte entusiasme for computere med. Paul og Bill brugte en teletypeterminal på deres high school, Lakeside, til at udvikle deres programmeringsevner på adskillige time-sharing computersystemer."""
text_fr = """Paul Allen est né le 21 janvier 1953 à Seattle, Washington, de Kenneth Sam Allen et Edna Faye Allen. Allen a fréquenté la Lakeside School, une école privée de Seattle, où il s'est lié d'amitié avec Bill Gates, de deux ans son cadet, avec qui il partageait un enthousiasme pour les ordinateurs. Paul et Bill ont utilisé un terminal de téléscripteur à leur lycée, Lakeside, pour développer leurs compétences en programmation sur plusieurs systèmes informatiques à temps partagé."""
text_es = """Paul Allen nació el 21 de enero de 1953 en Seattle, Washington, hijo de Kenneth Sam Allen y Edna Faye Allen. Allen asistió a Lakeside School, una escuela privada en Seattle, donde se hizo amigo de Bill Gates, dos años más joven, con quien compartió el entusiasmo por las computadoras. Paul y Bill usaron una terminal de teletipo en su escuela secundaria, Lakeside, para desarrollar sus habilidades de programación en varios sistemas informáticos de tiempo compartido."""

for text in [text_en, text_nl, text_de, text_dk, text_fr, text_es]:
    print(predictor.predict(text))
